version: "3.8"

services:
  lein-app:
    container_name: screener-lein
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "36096:36096"
    networks:
      - screener
    depends_on:
      - postgres-db
      - mongo-db

  postgres-db:
    container_name: screener-pgdb
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - screener
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: /Users/htellechea/p_projects/screener/db/create_tables.sql
        target: /usr/local/etc/create_tables.sql
      - type: bind
        source: /Users/htellechea/p_projects/screener/docker_init/postgres
        target: /docker-entrypoint-initdb.d

  mongo-db:
    container_name: screener-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - screener
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: bind
        source: /Users/htellechea/p_projects/screener/docker-init/mongo
        target: /docker-entrypoint-initdb.d

networks:
  screener:
    driver: bridge

volumes:
  postgres-data:
  
